[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.3.0",
    "docling>=2.60.0",
    "langchain>=0.3.27",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.3.31",
    "langchain-core>=0.3.79",
    "langchain-docling>=1.1.0",
    "langchain-huggingface>=0.3.1",
    "langchain-milvus>=0.2.1",
    "langchain-ollama>=0.3.10",
    "langchain-text-splitters>=0.3.11",
    "ollama>=0.6.0",
    "onnxruntime>=1.23.2",
    "pymilvus[milvus-lite]>=2.6.3",
    "pypdf>=6.1.3",
    "python-dotenv>=1.2.1",
    "transformers>=4.57.1",
]

[dependency-groups]
dev = [
    "iprogress>=0.4",
    "ipykernel>=7.1.0",
]
